// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using NUnit.Framework;

[TestFixture]
public class TC01IfUserIsInvalidTryAgainTest {
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }

    [SetUp]
    public void SetUp() {
    
        ChromeOptions options = new ChromeOptions();
        options.AddArgument("--headless=new");
        options.AddArgument("--window-size=1552,832");

        driver = new ChromeDriver(options);
        vars = new Dictionary<string, object>();
    }

    [TearDown]
    protected void TearDown() {
        driver?.Quit();
    }

    [Test]
    public void tC01IfUserIsInvalidTryAgain() {
    
        driver.Navigate().GoToUrl("https://www.saucedemo.com/");

        driver.FindElement(By.CssSelector("[data-test=\"username\"]"))
            .SendKeys("user123");

        driver.FindElement(By.CssSelector("[data-test=\"password\"]"))
            .SendKeys("secret_sauce");

        driver.FindElement(By.CssSelector("[data-test=\"login-button\"]"))
            .Click();

        vars["errorMessage"] = driver
            .FindElement(By.CssSelector("[data-test=\"error\"]"))
            .Text;

        Assert.That(
            vars["errorMessage"],
            Is.EqualTo("Epic sadface: Username and password do not match any user in this service")
        );

        Console.WriteLine("Wrong username");

        driver.FindElement(By.CssSelector("[data-test=\"username\"]"))
            .Clear();

        driver.FindElement(By.CssSelector("[data-test=\"username\"]"))
            .SendKeys("standard_user");

        driver.FindElement(By.CssSelector("[data-test=\"login-button\"]"))
            .Click();

        Assert.That(
            driver.FindElement(By.CssSelector("[data-test=\"title\"]")).Text,
            Is.EqualTo("Products")
        );

        Console.WriteLine("Successful login");
    }
}