pipeline {
    agent any

    options {
        skipDefaultCheckout(true)
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Restore') {
            steps {
                dir('7.Exercise-CI-CD-Jenkins/05-SeleniumIDE') {
                    bat 'dotnet restore SeleniumIde.sln'
                }
            }
        }

        stage('Build') {
            steps {
                dir('7.Exercise-CI-CD-Jenkins/05-SeleniumIDE') {
                    bat 'dotnet build SeleniumIde.sln --no-restore'
                }
            }
        }

        stage('Test') {
            steps {
                dir('7.Exercise-CI-CD-Jenkins/05-SeleniumIDE') {
                    bat 'dotnet test SeleniumIde.sln --no-build --logger trx'
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: '7.Exercise-CI-CD-Jenkins/05-SeleniumIDE/**/TestResults/*.trx',
                             allowEmptyArchive: true
        }
    }
}