pipeline {
    agent any

    options {
        skipDefaultCheckout(true)
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Check Node.js') {
            steps {
                bat 'node --version'
                bat 'call npm.cmd --version'
            }
        }

        stage('Install dependencies') {
            steps {
                dir('7.Exercise-CI-CD-Jenkins/02-Student-Registry-App-Docker') {
                    bat 'call npm.cmd ci'
                }
            }
        }

        stage('Run tests') {
            steps {
                dir('7.Exercise-CI-CD-Jenkins/02-Student-Registry-App-Docker') {
                    bat 'call npm.cmd test'
                }
            }
        }
    }
}