pipeline {
    agent any

    options {
        skipDefaultCheckout(true)
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Check .NET SDK') {
            steps {
                bat 'dotnet --version'
            }
        }

        stage('Restore') {
            steps {
                dir('7.Exercise-CI-CD-Jenkins/04-House-Renting-System-App') {
                    bat 'dotnet restore HouseRentingSystem.sln'
                }
            }
        }

        stage('Build') {
            steps {
                dir('7.Exercise-CI-CD-Jenkins/04-House-Renting-System-App') {
                    bat 'dotnet build HouseRentingSystem.sln --no-restore'
                }
            }
        }

        stage('Test') {
            steps {
                dir('7.Exercise-CI-CD-Jenkins/04-House-Renting-System-App') {
                    bat 'dotnet test HouseRentingSystem.sln --no-build --logger trx'
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: '7.Exercise-CI-CD-Jenkins/04-House-Renting-System-App/**/TestResults/*.trx',
                             allowEmptyArchive: true
        }
    }
}